services:
  # db:
  #   image: postgres:15
  #   container_name: questlog-db
  #   environment:
  #     POSTGRES_USER: questlog
  #     POSTGRES_PASSWORD: questlog
  #     POSTGRES_DB: questlog
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  backend:
    build: ./backend
    container_name: questlog-backend
    environment:
      DATABASE_URL: postgresql://neondb_owner:npg_QKejS25FPvZi@ep-spring-mode-ah293pmh-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      FRONTEND_URL: http://localhost:5173
    # depends_on:
    #   - db
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      # - /app/node_modules
    # command: npx nodemon src/server.js
    command: sh -c "npm install && npx prisma generate && npx nodemon src/server.js"
  frontend:
    build: ./frontend
    container_name: questlog-frontend
    environment:
      VITE_BACKEND_URL: http://localhost:3000
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
  ollama-embed:
    image: ollama/ollama:latest
    container_name: questlog-ollama-embed
    volumes:
      -ollama_embed_data:/root/.ollama
    ports:
      -"11434:11434"  
volumes:
  ollama_embed_data:
#   postgres_data:
