services:
  db:
    image: postgres:15
    container_name: questlog-db
    environment:
      POSTGRES_USER: questlog
      POSTGRES_PASSWORD: questlog
      POSTGRES_DB: questlog
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    container_name: questlog-backend
    environment:
      DATABASE_URL: postgresql://questlog:questlog@db:5432/questlog
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npx nodemon src/index.js
  frontend:
    build: ./frontend
    container_name: questlog-frontend
    environment:
      BACKEND_URL : http://localhost:3000
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
volumes:
  postgres_data:
